### ISSUE TITLE
可以有多个programs.yml　这种配置文件吗？执行不同的进程吗？

### ISSUE THREAD

**Issue by leeyongda** [codeskyblue/gosuv#32]

**Comment by codeskyblue** [comment]
如果弄成多个配置文件，网页端去修改配置文件就不好弄了

**Comment by caoye126** [comment]
建议做个conf.d 加载配置目录,这样大批量服务器方便管理,毕竟web页面只适合少量服务器环境,望采纳!

**Comment by codeskyblue** [comment]
没思路呀

**Comment by modeyang** [comment]
类型于supervisor include指令一样，利用glob或者正则将符合条件的文件读取出去，和你在program.yml中加载全部应用是一样的道理。
