### ISSUE TITLE
请教下怎么安装? 我用文档中的两种方法都安装失败了

### ISSUE THREAD

**Issue by zhangjianpinghik** [codeskyblue/gosuv#49]
@codeskyblue  

我是在ubuntu上的安装的,用文档中的两种方法都安装失败了
root@ubuntu:/home/sysadmin# curl -k https://raw.githubusercontent.com/codeskyblue/gosuv/master/get.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     24      0 --:--:-- --:--:-- --:--:--    25
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<h2>Moved</h2>'

root@ubuntu:/home/sysadmin# go get -d github.com/codeskyblue/gosuv
# cd .; git clone https://github.com/codeskyblue/gosuv /home/sysadmin/gocode/src/github.com/codeskyblue/gosuv
Cloning into '/home/sysadmin/gocode/src/github.com/codeskyblue/gosuv'...
fatal: http://5.5.5.15:80/slogin/index.htm?vlanid=0&url=https://github.com/codeskyblue/gosuv/info/refs not valid: is this a git repository?
package github.com/codeskyblue/gosuv: exit status 128

**Comment by codeskyblue** [comment]
网络很差呀， 直接去这里下载吧 https://github.com/codeskyblue/gosuv/releases

**Comment by zhangjianpinghik** [comment]
@codeskyblue   请教下源码的话如何编译安装?

**Comment by zhangjianpinghik** [comment]
已解决
