### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by thomaszdxsn** [codeskyblue/gosuv#61]
Hi, 最近发生一个很难才找到的bug..

在服务器端，我修改了时区为Asia/Shanghai，使用的方法是定义TZ环境变量。

正常运行程序，一切正常.

然而，在用gosuv启动的时候，发现时区变为了UTC~

这种行为是正常的吗

**Comment by codeskyblue** [comment]
gosuv是集成的系统变量。感觉可能是没有export TZ这个变量

**Comment by thomaszdxsn** [comment]
我现在回想起来，好像是先启动gosuv，再修改TZ变量。

所以应该是我的个人错误，sorry。
