### ISSUE TITLE
第一次执行的命令失败为何不报错

### ISSUE THREAD

**Issue by DoctorQ** [codeskyblue/gosuv#70]
# 问题描述

```
bin/gosuv -c conf/config.yml start-server
```

启动命令为

```
pipenv1
```

当我启动程序时，虽然这个pipenv1执行的时候报错了，但是gosuv仍然打印了:

```
server started, listening  .gosuv.sock
```

造成我以为程序执行成功了，但是这种情况gosuv为何不报错了？

我看了下actions里面的源码，发现作者并没有对命令的执行结果做任何异常处理，有点疑惑

```
if c.Bool("foreground") {
		suv.AutoStartPrograms()
		log.Printf("server listen on %v", addr)
		log.Fatal(http.ListenAndServe(addr, nil))
} else {
....
}

```

# 疑惑

是故意这么设计的么，对第一次启动不做处理？即使执行失败，也让gosuv监听这种错误的脚本。

**Comment by codeskyblue** [comment]
这个项目很久不维护了，非常感谢你的关注。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
